run:
  tests: false

linters:
  disable-all: false
  enable-all: true
  disable:
    - exhaustive
    - exhaustivestruct
    - wrapcheck
    - gci
    - forbidigo
    - goerr113
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gofumpt
    - gomnd
    - lll
    - nakedret
    - testpackage
    - wsl
