
env = "development"

[storage]
dsn = "host=host.docker.internal user=banner password=123456 dbname=banner sslmode=disable"

[logger]
level = "info"
path = "./logs/logfile.log"

[http]
host=""
port="4500"
