name: golangci
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34

  test:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: Checkout code
      - uses: actions/checkout@v2
      - run: go version
